//! Subscription offer tools: introductory, promotional, and win-back offers (#8, #10).
//!
//! Schemas verified against Apple's generated OpenAPI models. Promotional and
//! win-back offers carry their per-territory prices as `included`
//! resources linked by `${...}` temporary ids (the format App Store Connect
//! requires for inline creates).

use rmcp::{
    handler::server::wrapper::Parameters, model::*, schemars, tool, tool_router,
    ErrorData as McpError,
};
use serde::Deserialize;
use serde_json::{json, Value};

use super::AppStoreServer;

/// How an offer charges the customer.
#[derive(Debug, Clone, Copy, Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub(crate) enum SubscriptionOfferMode {
    PayAsYouGo,
    PayUpFront,
    FreeTrial,
}

impl SubscriptionOfferMode {
    pub(crate) fn as_api(self) -> &'static str {
        match self {
            SubscriptionOfferMode::PayAsYouGo => "PAY_AS_YOU_GO",
            SubscriptionOfferMode::PayUpFront => "PAY_UP_FRONT",
            SubscriptionOfferMode::FreeTrial => "FREE_TRIAL",
        }
    }
}

/// How long a single offer period lasts.
#[derive(Debug, Clone, Copy, Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub(crate) enum OfferDuration {
    ThreeDays,
    OneWeek,
    TwoWeeks,
    OneMonth,
    TwoMonths,
    ThreeMonths,
    SixMonths,
    OneYear,
}

impl OfferDuration {
    pub(crate) fn as_api(self) -> &'static str {
        match self {
            OfferDuration::ThreeDays => "THREE_DAYS",
            OfferDuration::OneWeek => "ONE_WEEK",
            OfferDuration::TwoWeeks => "TWO_WEEKS",
            OfferDuration::OneMonth => "ONE_MONTH",
            OfferDuration::TwoMonths => "TWO_MONTHS",
            OfferDuration::ThreeMonths => "THREE_MONTHS",
            OfferDuration::SixMonths => "SIX_MONTHS",
            OfferDuration::OneYear => "ONE_YEAR",
        }
    }
}

/// Win-back offer priority.
#[derive(Debug, Clone, Copy, Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum WinBackPriority {
    High,
    Normal,
}

impl WinBackPriority {
    fn as_api(self) -> &'static str {
        match self {
            WinBackPriority::High => "HIGH",
            WinBackPriority::Normal => "NORMAL",
        }
    }
}

/// Whether a win-back offer is promoted on the product page.
#[derive(Debug, Clone, Copy, Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum WinBackPromotionIntent {
    NotPromoted,
    UseAutoGeneratedAssets,
}

impl WinBackPromotionIntent {
    fn as_api(self) -> &'static str {
        match self {
            WinBackPromotionIntent::NotPromoted => "NOT_PROMOTED",
            WinBackPromotionIntent::UseAutoGeneratedAssets => "USE_AUTO_GENERATED_ASSETS",
        }
    }
}

/// A per-territory price for an offer (territory + price-point pair).
#[derive(Debug, Clone, Deserialize, schemars::JsonSchema)]
pub struct OfferPrice {
    /// Territory ID, e.g. "USA".
    pub territory: String,
    /// The subscriptionPricePoint ID (from list_subscription_price_points).
    pub price_point_id: String,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct CreateIntroOfferArgs {
    /// The subscription ID.
    pub subscription_id: String,
    /// Offer duration (one period's length).
    pub duration: OfferDuration,
    /// Charge mode.
    pub offer_mode: SubscriptionOfferMode,
    /// Number of periods the offer applies for.
    pub number_of_periods: u32,
    /// Price-point ID — required for PAY_AS_YOU_GO / PAY_UP_FRONT; omit for FREE_TRIAL.
    #[serde(default)]
    pub price_point_id: Option<String>,
    /// Territory for the price point (e.g. "USA"); pair with price_point_id.
    #[serde(default)]
    pub territory: Option<String>,
    /// Optional ISO-8601 start date (YYYY-MM-DD).
    #[serde(default)]
    pub start_date: Option<String>,
    /// Optional ISO-8601 end date (YYYY-MM-DD).
    #[serde(default)]
    pub end_date: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct CreatePromoOfferArgs {
    /// The subscription ID.
    pub subscription_id: String,
    /// Reference name (not customer-facing).
    pub name: String,
    /// The promotional offer code identifier (used by your app to invoke the offer).
    pub offer_code: String,
    /// Offer duration.
    pub duration: OfferDuration,
    /// Charge mode.
    pub offer_mode: SubscriptionOfferMode,
    /// Number of periods.
    pub number_of_periods: u32,
    /// One price per territory (at least one required).
    pub prices: Vec<OfferPrice>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct CreateWinBackOfferArgs {
    /// The subscription ID.
    pub subscription_id: String,
    /// Reference name (not customer-facing).
    pub reference_name: String,
    /// The offer identifier used by your app/StoreKit.
    pub offer_id: String,
    /// Offer duration.
    pub duration: OfferDuration,
    /// Charge mode.
    pub offer_mode: SubscriptionOfferMode,
    /// Number of periods.
    pub period_count: u32,
    /// Eligibility: minimum total months the customer previously paid.
    pub paid_subscription_duration_in_months: u32,
    /// Eligibility: minimum months since the customer last subscribed.
    #[serde(default)]
    pub months_since_last_subscribed_min: Option<u32>,
    /// Eligibility: maximum months since the customer last subscribed.
    #[serde(default)]
    pub months_since_last_subscribed_max: Option<u32>,
    /// Eligibility: minimum months to wait between offers.
    #[serde(default)]
    pub wait_between_offers_in_months: Option<u32>,
    /// ISO-8601 start date (YYYY-MM-DD), required.
    pub start_date: String,
    /// Optional ISO-8601 end date.
    #[serde(default)]
    pub end_date: Option<String>,
    /// Offer priority.
    pub priority: WinBackPriority,
    /// Whether/how the offer is promoted.
    #[serde(default)]
    pub promotion_intent: Option<WinBackPromotionIntent>,
    /// One price per territory (at least one required).
    pub prices: Vec<OfferPrice>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct ListWinBackOffersArgs {
    /// The subscription ID.
    pub subscription_id: String,
    /// Page size (max 200).
    #[serde(default)]
    pub limit: Option<u32>,
}

#[tool_router(router = offers_router, vis = "pub(crate)")]
impl AppStoreServer {
    /// Create an introductory offer for a subscription.
    #[tool(
        description = "Create a subscription introductory offer (free trial / pay-as-you-go / \
pay-up-front). For paid modes supply price_point_id + territory; for FREE_TRIAL omit them."
    )]
    async fn create_introductory_offer(
        &self,
        Parameters(args): Parameters<CreateIntroOfferArgs>,
    ) -> Result<CallToolResult, McpError> {
        let body = introductory_offer_body(&args);
        let value = self
            .client
            .post("/v1/subscriptionIntroductoryOffers", body)
            .await
            .map_err(AppStoreServer::map_err)?;
        self.ok_json(value)
    }

    /// Create a promotional offer for a subscription.
    #[tool(
        description = "Create a subscription promotional offer with a code and one price per \
territory. Look up price-point IDs with list_subscription_price_points."
    )]
    async fn create_promotional_offer(
        &self,
        Parameters(args): Parameters<CreatePromoOfferArgs>,
    ) -> Result<CallToolResult, McpError> {
        let body = promotional_offer_body(&args);
        let value = self
            .client
            .post("/v1/subscriptionPromotionalOffers", body)
            .await
            .map_err(AppStoreServer::map_err)?;
        self.ok_json(value)
    }

    /// Create a win-back offer for a subscription.
    #[tool(
        description = "Create a win-back offer to re-acquire churned subscribers (iOS 18+): \
eligibility windows, priority, and one price per territory."
    )]
    async fn create_winback_offer(
        &self,
        Parameters(args): Parameters<CreateWinBackOfferArgs>,
    ) -> Result<CallToolResult, McpError> {
        let body = winback_offer_body(&args);
        let value = self
            .client
            .post("/v1/winBackOffers", body)
            .await
            .map_err(AppStoreServer::map_err)?;
        self.ok_json(value)
    }

    /// List a subscription's win-back offers.
    #[tool(description = "List the win-back offers configured for a subscription.")]
    async fn list_winback_offers(
        &self,
        Parameters(args): Parameters<ListWinBackOffersArgs>,
    ) -> Result<CallToolResult, McpError> {
        let mut query = Vec::new();
        super::push_opt(&mut query, "limit", args.limit);
        let value = self
            .client
            .get(
                &format!("/v1/subscriptions/{}/winBackOffers", args.subscription_id),
                &query,
            )
            .await
            .map_err(AppStoreServer::map_err)?;
        self.ok_json(value)
    }
}

// ---- Pure JSON:API document builders (unit-tested below) --------------------

/// Build `(relationship refs, included resources)` for a list of offer prices,
/// linked by `${price0}`, `${price1}`, ... temporary ids.
pub(crate) fn inline_offer_prices(
    price_type: &str,
    prices: &[OfferPrice],
) -> (Vec<Value>, Vec<Value>) {
    let mut refs = Vec::with_capacity(prices.len());
    let mut included = Vec::with_capacity(prices.len());
    for (i, p) in prices.iter().enumerate() {
        let temp = format!("${{price{i}}}");
        refs.push(json!({ "type": price_type, "id": temp }));
        included.push(json!({
            "type": price_type,
            "id": temp,
            "relationships": {
                "territory": { "data": { "type": "territories", "id": p.territory } },
                "subscriptionPricePoint": {
                    "data": { "type": "subscriptionPricePoints", "id": p.price_point_id }
                }
            }
        }));
    }
    (refs, included)
}

fn introductory_offer_body(args: &CreateIntroOfferArgs) -> Value {
    let mut attrs = json!({
        "duration": args.duration.as_api(),
        "offerMode": args.offer_mode.as_api(),
        "numberOfPeriods": args.number_of_periods,
    });
    if let Some(s) = &args.start_date {
        attrs["startDate"] = json!(s);
    }
    if let Some(e) = &args.end_date {
        attrs["endDate"] = json!(e);
    }
    let mut rels = json!({
        "subscription": { "data": { "type": "subscriptions", "id": args.subscription_id } }
    });
    if let Some(pp) = &args.price_point_id {
        rels["subscriptionPricePoint"] =
            json!({ "data": { "type": "subscriptionPricePoints", "id": pp } });
    }
    if let Some(t) = &args.territory {
        rels["territory"] = json!({ "data": { "type": "territories", "id": t } });
    }
    json!({
        "data": {
            "type": "subscriptionIntroductoryOffers",
            "attributes": attrs,
            "relationships": rels
        }
    })
}

fn promotional_offer_body(args: &CreatePromoOfferArgs) -> Value {
    let (refs, included) = inline_offer_prices("subscriptionPromotionalOfferPrices", &args.prices);
    json!({
        "data": {
            "type": "subscriptionPromotionalOffers",
            "attributes": {
                "name": args.name,
                "offerCode": args.offer_code,
                "duration": args.duration.as_api(),
                "offerMode": args.offer_mode.as_api(),
                "numberOfPeriods": args.number_of_periods,
            },
            "relationships": {
                "subscription": { "data": { "type": "subscriptions", "id": args.subscription_id } },
                "prices": { "data": refs }
            }
        },
        "included": included
    })
}

fn winback_offer_body(args: &CreateWinBackOfferArgs) -> Value {
    let (refs, included) = inline_offer_prices("winBackOfferPrices", &args.prices);
    let mut time_range = json!({});
    if let Some(m) = args.months_since_last_subscribed_min {
        time_range["minimum"] = json!(m);
    }
    if let Some(m) = args.months_since_last_subscribed_max {
        time_range["maximum"] = json!(m);
    }
    let mut attrs = json!({
        "referenceName": args.reference_name,
        "offerId": args.offer_id,
        "duration": args.duration.as_api(),
        "offerMode": args.offer_mode.as_api(),
        "periodCount": args.period_count,
        "customerEligibilityPaidSubscriptionDurationInMonths": args.paid_subscription_duration_in_months,
        "customerEligibilityTimeSinceLastSubscribedInMonths": time_range,
        "startDate": args.start_date,
        "priority": args.priority.as_api(),
    });
    if let Some(w) = args.wait_between_offers_in_months {
        attrs["customerEligibilityWaitBetweenOffersInMonths"] = json!(w);
    }
    if let Some(e) = &args.end_date {
        attrs["endDate"] = json!(e);
    }
    if let Some(pi) = args.promotion_intent {
        attrs["promotionIntent"] = json!(pi.as_api());
    }
    json!({
        "data": {
            "type": "winBackOffers",
            "attributes": attrs,
            "relationships": {
                "subscription": { "data": { "type": "subscriptions", "id": args.subscription_id } },
                "prices": { "data": refs }
            }
        },
        "included": included
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn price() -> OfferPrice {
        OfferPrice {
            territory: "USA".into(),
            price_point_id: "pp-1".into(),
        }
    }

    #[test]
    fn intro_offer_free_trial_omits_price_relationships() {
        let args = CreateIntroOfferArgs {
            subscription_id: "sub-1".into(),
            duration: OfferDuration::OneWeek,
            offer_mode: SubscriptionOfferMode::FreeTrial,
            number_of_periods: 1,
            price_point_id: None,
            territory: None,
            start_date: None,
            end_date: None,
        };
        let b = introductory_offer_body(&args);
        assert_eq!(b["data"]["type"], "subscriptionIntroductoryOffers");
        assert_eq!(b["data"]["attributes"]["offerMode"], "FREE_TRIAL");
        assert_eq!(b["data"]["attributes"]["duration"], "ONE_WEEK");
        assert_eq!(b["data"]["attributes"]["numberOfPeriods"], 1);
        let rels = &b["data"]["relationships"];
        assert_eq!(rels["subscription"]["data"]["id"], "sub-1");
        assert!(rels.get("subscriptionPricePoint").is_none());
        assert!(rels.get("territory").is_none());
    }

    #[test]
    fn intro_offer_paid_includes_price_point_and_territory() {
        let args = CreateIntroOfferArgs {
            subscription_id: "sub-1".into(),
            duration: OfferDuration::ThreeMonths,
            offer_mode: SubscriptionOfferMode::PayAsYouGo,
            number_of_periods: 3,
            price_point_id: Some("pp-9".into()),
            territory: Some("USA".into()),
            start_date: Some("2026-07-01".into()),
            end_date: None,
        };
        let b = introductory_offer_body(&args);
        assert_eq!(b["data"]["attributes"]["offerMode"], "PAY_AS_YOU_GO");
        assert_eq!(b["data"]["attributes"]["startDate"], "2026-07-01");
        assert!(b["data"]["attributes"].get("endDate").is_none());
        let rels = &b["data"]["relationships"];
        assert_eq!(
            rels["subscriptionPricePoint"]["data"]["type"],
            "subscriptionPricePoints"
        );
        assert_eq!(rels["subscriptionPricePoint"]["data"]["id"], "pp-9");
        assert_eq!(rels["territory"]["data"]["id"], "USA");
    }

    #[test]
    fn promo_offer_links_included_prices_by_temp_id() {
        let args = CreatePromoOfferArgs {
            subscription_id: "sub-1".into(),
            name: "Summer".into(),
            offer_code: "SUMMER".into(),
            duration: OfferDuration::OneMonth,
            offer_mode: SubscriptionOfferMode::PayUpFront,
            number_of_periods: 1,
            prices: vec![
                price(),
                OfferPrice {
                    territory: "GBR".into(),
                    price_point_id: "pp-2".into(),
                },
            ],
        };
        let b = promotional_offer_body(&args);
        assert_eq!(b["data"]["type"], "subscriptionPromotionalOffers");
        assert_eq!(b["data"]["attributes"]["offerCode"], "SUMMER");
        let refs = b["data"]["relationships"]["prices"]["data"]
            .as_array()
            .unwrap();
        let included = b["included"].as_array().unwrap();
        assert_eq!(refs.len(), 2);
        assert_eq!(included.len(), 2);
        assert_eq!(refs[0]["id"], "${price0}");
        assert_eq!(included[0]["id"], "${price0}");
        assert_eq!(included[0]["type"], "subscriptionPromotionalOfferPrices");
        assert_eq!(
            included[0]["relationships"]["territory"]["data"]["id"],
            "USA"
        );
        assert_eq!(
            included[1]["relationships"]["subscriptionPricePoint"]["data"]["id"],
            "pp-2"
        );
    }

    #[test]
    fn winback_offer_body_has_required_attributes_and_prices() {
        let args = CreateWinBackOfferArgs {
            subscription_id: "sub-1".into(),
            reference_name: "WinBack".into(),
            offer_id: "winback1".into(),
            duration: OfferDuration::OneMonth,
            offer_mode: SubscriptionOfferMode::PayAsYouGo,
            period_count: 3,
            paid_subscription_duration_in_months: 6,
            months_since_last_subscribed_min: Some(1),
            months_since_last_subscribed_max: Some(12),
            wait_between_offers_in_months: None,
            start_date: "2026-07-01".into(),
            end_date: None,
            priority: WinBackPriority::High,
            promotion_intent: Some(WinBackPromotionIntent::UseAutoGeneratedAssets),
            prices: vec![price()],
        };
        let b = winback_offer_body(&args);
        let attrs = &b["data"]["attributes"];
        assert_eq!(b["data"]["type"], "winBackOffers");
        assert_eq!(attrs["offerId"], "winback1");
        assert_eq!(attrs["periodCount"], 3);
        assert_eq!(attrs["priority"], "HIGH");
        assert_eq!(attrs["promotionIntent"], "USE_AUTO_GENERATED_ASSETS");
        assert_eq!(
            attrs["customerEligibilityPaidSubscriptionDurationInMonths"],
            6
        );
        let range = &attrs["customerEligibilityTimeSinceLastSubscribedInMonths"];
        assert_eq!(range["minimum"], 1);
        assert_eq!(range["maximum"], 12);
        assert!(attrs
            .get("customerEligibilityWaitBetweenOffersInMonths")
            .is_none());
        assert_eq!(b["included"][0]["type"], "winBackOfferPrices");
        assert_eq!(
            b["data"]["relationships"]["prices"]["data"][0]["id"],
            "${price0}"
        );
    }
}
