//! Apple's App Store Connect OpenAPI spec, embedded and indexed.
//!
//! `spec/asc-openapi.json.gz` is generated by `scripts/update_spec.py` from
//! Apple's published spec: every operation's method, path, tags, query
//! parameters and request/response schema names, plus all component schemas,
//! with prose stripped. It is decompressed once, on first use.
//!
//! Three things are built on it: searching operations by words, describing one
//! operation (its parameters and its request body with `$ref`s resolved), and
//! checking a request against the spec before it is sent, so an agent learns
//! about a misspelled filter, a missing required parameter or an attribute
//! Apple does not define from this server rather than from a bare 4xx.

use std::collections::BTreeSet;
use std::io::Read;
use std::sync::OnceLock;

use serde::Deserialize;
use serde_json::{json, Map, Value};

static SPEC_GZ: &[u8] = include_bytes!("../spec/asc-openapi.json.gz");
static SPEC: OnceLock<Spec> = OnceLock::new();

/// How deep `describe` expands nested `$ref`s before printing just the name.
const DESCRIBE_DEPTH: usize = 6;

#[derive(Debug, Deserialize)]
pub struct Spec {
    pub version: String,
    pub operations: Vec<Operation>,
    pub schemas: Map<String, Value>,
}

#[derive(Debug, Deserialize)]
pub struct Operation {
    pub id: String,
    pub method: String,
    pub path: String,
    pub tags: Vec<String>,
    pub deprecated: bool,
    pub params: Vec<Param>,
    pub body: Option<String>,
    pub response: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct Param {
    pub name: String,
    pub required: bool,
    pub schema: Value,
}

/// The embedded spec, decompressed and parsed on first use.
pub fn spec() -> &'static Spec {
    SPEC.get_or_init(|| {
        let mut raw = Vec::new();
        flate2::read::GzDecoder::new(SPEC_GZ)
            .read_to_end(&mut raw)
            .expect("embedded spec is valid gzip");
        serde_json::from_slice(&raw).expect("embedded spec is valid JSON")
    })
}

// ---- Search ------------------------------------------------------------------

/// Split an identifier or phrase into lowercase words: `appStoreVersions_get`
/// → `app store versions get`; `/v1/apps/{id}` → `v1 apps id`.
fn words(s: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut cur = String::new();
    let mut prev_lower = false;
    for ch in s.chars() {
        if ch.is_alphanumeric() {
            if ch.is_uppercase() && prev_lower && !cur.is_empty() {
                out.push(std::mem::take(&mut cur));
            }
            prev_lower = ch.is_lowercase() || ch.is_ascii_digit();
            cur.extend(ch.to_lowercase());
        } else {
            if !cur.is_empty() {
                out.push(std::mem::take(&mut cur));
            }
            prev_lower = false;
        }
    }
    if !cur.is_empty() {
        out.push(cur);
    }
    out
}

/// Crude stemming so "subscription" matches "subscriptions" and "pricing"
/// matches "prices": an exact match, one word a prefix of the other (both at
/// least four letters), or a shared prefix of five letters or more.
fn word_matches(query: &str, word: &str) -> bool {
    if query == word {
        return true;
    }
    let (short, long) = if query.len() <= word.len() {
        (query, word)
    } else {
        (word, query)
    };
    if short.len() >= 4 && long.starts_with(short) {
        return true;
    }
    let common = query
        .bytes()
        .zip(word.bytes())
        .take_while(|(a, b)| a == b)
        .count();
    common >= 5 || (common >= 4 && short.len() <= 6)
}

/// The verb a method stands for, so "create", "delete" or "update" in a query
/// favour the matching method.
fn method_words(method: &str) -> &'static [&'static str] {
    match method {
        "GET" => &["get", "list", "read", "fetch", "show", "find"],
        "POST" => &["create", "add", "new", "submit", "upload", "post", "start"],
        "PATCH" => &["update", "edit", "change", "set", "modify", "patch"],
        "PUT" => &["update", "set", "put"],
        "DELETE" => &["delete", "remove", "cancel"],
        _ => &[],
    }
}

/// Score every operation against the query and return the best `limit`.
/// Relationship-linkage endpoints (`/relationships/`) rank below the resource
/// endpoints they mirror, since an agent almost always wants the latter.
pub fn search(query: &str, method: Option<&str>, limit: usize) -> Vec<&'static Operation> {
    let spec = spec();
    let terms: Vec<String> = words(query);
    if terms.is_empty() {
        return Vec::new();
    }
    let method = method.map(|m| m.trim().to_ascii_uppercase());
    let mut scored: Vec<(i64, &Operation)> = spec
        .operations
        .iter()
        .filter(|op| method.as_deref().is_none_or(|m| op.method == m))
        .filter_map(|op| {
            let path_words = words(&op.path);
            let id_words = words(&op.id);
            let tag_words: Vec<String> = op.tags.iter().flat_map(|t| words(t)).collect();
            let mut score = 0i64;
            let mut matched = 0usize;
            for term in &terms {
                let mut hit = 0i64;
                // The last path segment names what the operation returns.
                if path_words
                    .last()
                    .is_some_and(|w| word_matches(term, w))
                {
                    hit = hit.max(6);
                }
                if path_words.iter().any(|w| word_matches(term, w)) {
                    hit = hit.max(4);
                }
                if id_words.iter().any(|w| word_matches(term, w)) {
                    hit = hit.max(3);
                }
                if tag_words.iter().any(|w| word_matches(term, w)) {
                    hit = hit.max(2);
                }
                if method_words(&op.method).contains(&term.as_str()) {
                    hit = hit.max(3);
                }
                if hit > 0 {
                    matched += 1;
                }
                score += hit;
            }
            if matched == 0 {
                return None;
            }
            // Every term matching beats a high score on a few.
            score += (matched as i64) * 10;
            if op.path.contains("/relationships/") {
                score -= 8;
            }
            if op.deprecated {
                score -= 5;
            }
            // Prefer shorter paths among equals: the top-level collection.
            score -= op.path.matches('/').count() as i64;
            Some((score, op))
        })
        .collect();
    scored.sort_by(|a, b| b.0.cmp(&a.0).then_with(|| a.1.path.cmp(&b.1.path)));
    scored.into_iter().take(limit).map(|(_, op)| op).collect()
}

/// One-line summary of an operation for search results.
pub fn summarize(op: &Operation) -> Value {
    let mut v = json!({
        "method": op.method,
        "path": op.path,
        "operationId": op.id,
    });
    if op.deprecated {
        v["deprecated"] = json!(true);
    }
    if let Some(body) = &op.body {
        v["body"] = json!(body);
    }
    v
}

// ---- Lookup ------------------------------------------------------------------

/// Strip scheme/host and query string so `https://api.appstoreconnect.apple.com/v1/apps?limit=1`
/// and `/v1/apps` both resolve to `/v1/apps`.
fn normalize_path(path: &str) -> String {
    let mut p = path.trim();
    if let Some(rest) = p.split_once("://").map(|(_, r)| r) {
        p = rest.find('/').map_or("", |i| &rest[i..]);
    }
    let p = p.split(['?', '#']).next().unwrap_or("");
    let p = p.trim_end_matches('/');
    if p.starts_with('/') {
        p.to_string()
    } else {
        format!("/{p}")
    }
}

fn template_matches(template: &str, path: &str) -> bool {
    let t: Vec<&str> = template.split('/').collect();
    let p: Vec<&str> = path.split('/').collect();
    t.len() == p.len()
        && t.iter().zip(&p).all(|(t, p)| {
            (t.starts_with('{') && t.ends_with('}') && !p.is_empty()) || t == p
        })
}

/// Find the operation for `method` + a concrete or templated path.
pub fn find(method: &str, path: &str) -> Option<&'static Operation> {
    let method = method.trim().to_ascii_uppercase();
    let path = normalize_path(path);
    let candidates = spec()
        .operations
        .iter()
        .filter(|op| op.method == method && template_matches(&op.path, &path));
    // A literal segment beats a `{id}` in the same position.
    candidates.max_by_key(|op| op.path.split('/').filter(|s| !s.starts_with('{')).count())
}

/// Operations that exist on `path` under any method, for "did you mean".
pub fn methods_for(path: &str) -> Vec<&'static str> {
    let path = normalize_path(path);
    spec()
        .operations
        .iter()
        .filter(|op| template_matches(&op.path, &path))
        .map(|op| op.method.as_str())
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect()
}

// ---- Describe ----------------------------------------------------------------

fn schema(name: &str) -> Option<&'static Value> {
    spec().schemas.get(name)
}

fn ref_target(v: &Value) -> Option<&str> {
    v.get("$ref")?.as_str()?.rsplit('/').next()
}

/// Resolve `$ref`s to `depth`, so the agent sees the body it has to send.
pub fn expand(v: &Value, depth: usize) -> Value {
    if let Some(name) = ref_target(v) {
        return match schema(name) {
            Some(target) if depth > 0 => expand(target, depth - 1),
            _ => json!({ "$ref": name }),
        };
    }
    match v {
        Value::Object(map) => Value::Object(
            map.iter()
                .map(|(k, v)| (k.clone(), expand(v, depth)))
                .collect(),
        ),
        Value::Array(items) => Value::Array(items.iter().map(|v| expand(v, depth)).collect()),
        other => other.clone(),
    }
}

/// Everything an agent needs to call one operation correctly.
pub fn describe(op: &Operation) -> Value {
    let params: Vec<Value> = op
        .params
        .iter()
        .map(|p| {
            let mut v = json!({ "name": p.name, "schema": p.schema });
            if p.required {
                v["required"] = json!(true);
            }
            v
        })
        .collect();
    let mut v = json!({
        "method": op.method,
        "path": op.path,
        "operationId": op.id,
        "tags": op.tags,
        "queryParameters": params,
        "returns": op.response,
    });
    if op.deprecated {
        v["deprecated"] = json!(true);
    }
    if let Some(body) = &op.body {
        v["requestBody"] = json!({
            "schema": body,
            "shape": schema(body).map(|s| expand(s, DESCRIBE_DEPTH)),
        });
    }
    v
}

// ---- Validate ----------------------------------------------------------------

/// Check query parameter names against the operation. Apple answers an
/// unknown parameter or a missing required one with a 400; catching it here
/// lets the error list what *is* allowed.
pub fn check_query(op: &Operation, query: &[(String, String)]) -> Vec<String> {
    let mut problems = Vec::new();
    for (name, _) in query {
        // `cursor` arrives inside `next` links and is not in the spec.
        if name == "cursor" || op.params.iter().any(|p| &p.name == name) {
            continue;
        }
        problems.push(format!("query parameter '{name}' is not accepted here"));
    }
    for p in op.params.iter().filter(|p| p.required) {
        if !query.iter().any(|(n, _)| n == &p.name) {
            problems.push(format!("query parameter '{}' is required", p.name));
        }
    }
    if !problems.is_empty() {
        let allowed: Vec<&str> = op.params.iter().map(|p| p.name.as_str()).collect();
        problems.push(format!("accepted: {}", allowed.join(", ")));
    }
    problems
}

/// Check a request body against the operation's schema. Returns one line per
/// problem, each with a JSON pointer.
pub fn check_body(op: &Operation, body: Option<&Value>) -> Vec<String> {
    match (&op.body, body) {
        (None, None) => Vec::new(),
        (None, Some(_)) => vec!["this operation takes no request body".into()],
        (Some(name), None) => vec![format!("a request body ({name}) is required")],
        (Some(name), Some(body)) => validate_named(name, body),
    }
}

/// Validate `value` against the named component schema.
pub fn validate_named(name: &str, value: &Value) -> Vec<String> {
    let mut problems = Vec::new();
    if let Some(s) = schema(name) {
        validate(s, value, "", &mut problems);
    }
    problems
}

fn type_name(v: &Value) -> &'static str {
    match v {
        Value::Null => "null",
        Value::Bool(_) => "boolean",
        Value::Number(n) if n.is_i64() || n.is_u64() => "integer",
        Value::Number(_) => "number",
        Value::String(_) => "string",
        Value::Array(_) => "array",
        Value::Object(_) => "object",
    }
}

fn validate(s: &Value, v: &Value, at: &str, out: &mut Vec<String>) {
    if let Some(name) = ref_target(s) {
        if let Some(target) = schema(name) {
            validate(target, v, at, out);
        }
        return;
    }
    if v.is_null() && s.get("nullable").and_then(Value::as_bool) == Some(true) {
        return;
    }
    for key in ["oneOf", "anyOf"] {
        if let Some(branches) = s.get(key).and_then(Value::as_array) {
            let mut best: Option<Vec<String>> = None;
            for b in branches {
                let mut errs = Vec::new();
                validate(b, v, at, &mut errs);
                if errs.is_empty() {
                    return;
                }
                if best.as_ref().is_none_or(|e| errs.len() < e.len()) {
                    best = Some(errs);
                }
            }
            out.extend(best.unwrap_or_default());
            return;
        }
    }
    if let Some(all) = s.get("allOf").and_then(Value::as_array) {
        for b in all {
            validate(b, v, at, out);
        }
    }
    let here = if at.is_empty() { "/" } else { at };
    if let Some(expected) = s.get("type").and_then(Value::as_str) {
        let actual = type_name(v);
        let ok = actual == expected || (expected == "number" && actual == "integer");
        if !ok {
            out.push(format!("{here}: expected {expected}, got {actual}"));
            return;
        }
    }
    if let Some(choices) = s.get("enum").and_then(Value::as_array) {
        if !choices.contains(v) {
            let list: Vec<String> = choices
                .iter()
                .map(|c| c.as_str().map_or_else(|| c.to_string(), str::to_string))
                .collect();
            out.push(format!("{here}: {v} is not one of {}", list.join(", ")));
        }
    }
    match v {
        Value::Object(map) => {
            let props = s.get("properties").and_then(Value::as_object);
            if let Some(required) = s.get("required").and_then(Value::as_array) {
                for r in required.iter().filter_map(Value::as_str) {
                    if !map.contains_key(r) {
                        out.push(format!("{at}/{r}: required"));
                    }
                }
            }
            if let Some(props) = props {
                for (k, child) in map {
                    match props.get(k) {
                        Some(ps) => validate(ps, child, &format!("{at}/{k}"), out),
                        None => {
                            let known: Vec<&str> = props.keys().map(String::as_str).collect();
                            out.push(format!(
                                "{at}/{k}: not defined by Apple here (known: {})",
                                known.join(", ")
                            ));
                        }
                    }
                }
            }
        }
        Value::Array(items) => {
            if let Some(item_schema) = s.get("items") {
                for (i, item) in items.iter().enumerate() {
                    validate(item_schema, item, &format!("{at}/{i}"), out);
                }
            }
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_embedded_spec_loads() {
        let s = spec();
        assert!(s.operations.len() > 1000, "{}", s.operations.len());
        assert!(s.schemas.contains_key("AppUpdateRequest"));
    }

    #[test]
    fn words_split_camel_case_and_paths() {
        assert_eq!(words("appStoreVersions_get"), ["app", "store", "versions", "get"]);
        assert_eq!(words("/v1/apps/{id}"), ["v1", "apps", "id"]);
    }

    #[test]
    fn search_finds_the_obvious_endpoint_first() {
        let top = search("webhooks", None, 5);
        assert!(top.iter().any(|o| o.path == "/v1/webhooks"), "{top:?}");
        let top = search("create webhook", Some("POST"), 3);
        assert_eq!(top[0].path, "/v1/webhooks");
        let top = search("sales reports", None, 3);
        assert_eq!(top[0].path, "/v1/salesReports");
    }

    #[test]
    fn find_resolves_concrete_paths_and_urls() {
        let op = find("patch", "/v1/apps/123").unwrap();
        assert_eq!(op.path, "/v1/apps/{id}");
        let op = find(
            "GET",
            "https://api.appstoreconnect.apple.com/v1/apps?limit=1",
        )
        .unwrap();
        assert_eq!(op.path, "/v1/apps");
        assert!(find("PUT", "/v1/apps").is_none());
        assert_eq!(methods_for("/v1/apps/1"), ["GET", "PATCH"]);
    }

    #[test]
    fn query_check_names_unknown_and_missing_parameters() {
        let op = find("GET", "/v1/apps").unwrap();
        let problems = check_query(op, &[("filter[nope]".into(), "x".into())]);
        assert!(problems[0].contains("filter[nope]"), "{problems:?}");
        assert!(check_query(op, &[("limit".into(), "5".into())]).is_empty());
    }

    #[test]
    fn body_check_catches_unknown_attributes_and_bad_enums() {
        let op = find("PATCH", "/v1/ageRatingDeclarations/1").unwrap();
        let body = json!({ "data": {
            "type": "ageRatingDeclarations", "id": "1",
            "attributes": { "gambling": "NONE", "violenceCartoonOrFantasy": "SOMETIMES", "madeUp": true }
        }});
        let problems = check_body(op, Some(&body));
        let joined = problems.join("\n");
        assert!(joined.contains("/data/attributes/gambling: expected boolean"), "{joined}");
        assert!(joined.contains("SOMETIMES"), "{joined}");
        assert!(joined.contains("/data/attributes/madeUp: not defined"), "{joined}");

        let good = json!({ "data": {
            "type": "ageRatingDeclarations", "id": "1",
            "attributes": { "gambling": false, "violenceCartoonOrFantasy": "NONE", "ageAssurance": false }
        }});
        assert!(check_body(op, Some(&good)).is_empty());
    }

    #[test]
    fn attributes_named_description_survive_preprocessing() {
        let op = find("PATCH", "/v1/appStoreVersionLocalizations/1").unwrap();
        let body = json!({ "data": {
            "type": "appStoreVersionLocalizations", "id": "1",
            "attributes": { "description": "An app." }
        }});
        assert!(check_body(op, Some(&body)).is_empty());
    }
}
